[package]
name = "oj"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints.rust]
dead_code = "allow"
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[dependencies]
oj-core = { path = "../core", version = "0.1.0" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
assert_cmd = "2"
nix = { version = "0.29", features = ["signal", "process"] }
predicates = "3"
serde_json = "1"
tempfile = "3"
